 - name: "Creating AWS image of this instance"
   amazon.aws.ec2_ami:
      instance_id: "{{ instance_id  }}"
      wait: yes
      name: Hadoop-JDK-AMI
      launch_permissions:
         group_names: ['all']
      tags:
         Name: Hadoop Map Reduce
         Service: Clusture

