- name: "Configuring mapred-site.xml file"
  template:
        src: "mapred-site.xml"
        dest: "/etc/hadoop/mapred-site.xml"
- name: "Telling Job Tracker to the address of HDFS Master"
  template:
        src: "core-site.xml"
        dest: "/etc/hadoop/core-site.xml"
- name: "Starting the Job Tracker"
  shell: "hadoop-daemon.sh start jobtracker"
- name: "Starting Permanently if you shutdown again start it will work"
  shell: "echo hadoop-daemon.sh start jobtracker >> /root/.bashrc"

